### ISSUE TITLE
Konfiguraatiossa olevat typot/virheet ovat vaikeita löytää

### ISSUE THREAD

**Issue by Svenskapojkarna** [CommunityHiQ/Frends.Community.Apache#2]
This issue is moved here from https://github.com/CommunityHiQ/Frends.Community.Apache.Parquet

Konfiguraation vikasietoisuus on pieni: jos siinä on yksikin typo, esim. "type" -> "typr" , niin taski ei sitä havaitse, vaan palauttaa poikkeuksen.

- Tämä voitaisiin välttää lisäämällä skeematarkastus ennen konfiguraation lukemista.
- Konfiguraation lukeminen voisi olla omassa try-catch rakenteessaan, josta pystyisi päättelemään onko vika skeemassa vai aineistossa.

**Comment by RikuVirtanen** [comment]
Korjattu tekemällä schema tarkistus, jossa tarkistetaan scheman oikeinkirjoitus.
